export enum DocumentType {
  HOJA_VIDA = 'a',
  DECLARACION_BIENES = 'b',
  CEDULA_FRONTAL = 'c_front',
  CEDULA_POSTERIOR = 'c_back',
  DIPLOMA_GRADO = 'd',
  TARJETA_PROFESIONAL = 'e',
  DIPLOMA_POSTGRADO = 'f',
  CERTIFICADO_EXPERIENCIA = 'g',
  CERTIFICADO_TRIBUTARIO = 'h',
  DECLARACION_INHABILIDADES = 'i',
  ANTECEDENTES_DISCIPLINARIOS = 'j',
  ANTECEDENTES_FISCALES = 'k',
  ANTECEDENTES_PENALES = 'l',
  REGISTRO_MEDIDAS_CORRECTIVAS = 'm',
  INHABILIDADES_DELITOS_SEXUALES = 'n'
}